### ISSUE TITLE
Front-end - old logos/names

### ISSUE THREAD

**Issue by peterkwells** [OpenReferralUK/human-services#48]
The ORUK [homepage](https://openreferraluk.org/) and [community page](https://openreferraluk.org/community/standard-community) lists FutureGov and MHCLG as members. Both organisations changed their names in 2021.

FutureGov are now [tpximpact](https://wearefuturegov.com/newsroom/becoming-tpximpact) and MHCLG are now [DLUHC](https://www.lgcplus.com/politics/mhclg-to-be-renamed-department-for-levelling-up-housing-and-communities-20-09-2021/)

(raised issue here as issues seem to be disabled on the website repo)

**Comment by MikeThacker1** [comment]
Thanks @peterkwells . We'll address that. I'll check if we should be enabling issues on the other repository.
