### ISSUE TITLE
eligibility.eligibility is insufficent

### ISSUE THREAD

**Issue by PorismDominicSkinner** [OpenReferralUK/human-services#6]
For eligibility the bucks data has young person, which dictionary definitions basically say is a teenager. Young adult which again says 18 to early 20's and older adult.  Unfortunately in the allowed values shown below we can't represent young adult.

The Open Activities data has issues with requirements being minimum age 16 or 18 again this isn't really represented. As it doesn't take into account minimum or maximum values.

We could also have toddler groups etc.

**Here are the allowed values.**

- adult
- child
- teen
- family
- female
- male
- Transgender
- Transgender - M to F
- Transgender - F to M

**Comment by MikeThacker1** [comment]
In line with the OpenCommunity discovery recommendation, we added minimum_age and maximum_age to the eligibility table. Other forms of eligibility are handles via taxonomies.
